### ISSUE TITLE
Parser signal interferes with debug-on-error

### ISSUE THREAD

**Issue by jimmywongroo** [emacs-lsp/lsp-origami#1]
There's no need to signal an error when visiting a buffer that does't have lsp mode turned on or support folding. If origami mode is turn on globally, this pops up the debugger every time a new buffer like the above is visited.

https://github.com/emacs-lsp/lsp-origami/blob/c7653602a2f2396b1a42d6053fd2be55fce8e0a2/lsp-origami.el#L55

**Comment by yyoncho** [comment]
@vibhavp we should enable the origami lsp provider only for lsp-mode buffers that have foldingRangeProvider.
