### ISSUE TITLE
Compare to eglot and origami

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [emacs-lsp/lsp-origami#16]
Hi,
I don't understand your package.

What is differnt from using `lsp-origima` and using `origami` with `eglot` (kind of an lsp-mode)?

**Comment by yyoncho** [comment]
Origami will be less precise and slower in determining the folding ranges because the ranges will be based on text parsing while the server can do semantic parsing because it understands the code much better.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
And should it work with eglot also instead of lsp-mode?

Is it an addon to origami so I need to install origami and lsp-origami or only the latter?

**Comment by yyoncho** [comment]
No, it uses lsp-mode's API, so it won't work with eglot.
