### ISSUE TITLE
dynamicRegistration with intelephense

### ISSUE THREAD

**Issue by tomterl** [emacs-lsp/lsp-origami#3]
I tried to test code-folding with intelephense -- the premium version supports it -- but it isn't detected as supported.

The issue is explained here: https://github.com/bmewburn/vscode-intelephense/issues/666 with hopefully all relevant parts of the client/server communication.

It would be nice if you could take a look at this.

**Comment by yyoncho** [comment]
Can you test https://github.com/emacs-lsp/lsp-origami/commit/1aa40a06fdf331ff0cb1f5a88de8e719400deaf4 ?

**Comment by tomterl** [comment]
Sorry for the delay -- the commit does not help, there's still the message
````
lsp--get-folding-ranges: Capability not supported by the language server: "foldingRangeProvider"
````

**Comment by yyoncho** [comment]
@tomterl there are few more places to be fixed in lsp-mode code I will update it and ping you to retest.

**Comment by tomterl** [comment]
@yyoncho thanks a lot! will do -- as with this time I may need a couple of days to react, I'm working only part time, and don't always have instant time to check, as much as I want to

**Comment by yyoncho** [comment]
No worries, we are not in a hurry...

Pushed https://github.com/yyoncho/lsp-mode/commit/7aa844f

**Comment by tomterl** [comment]
Cool - that solves the registration issue.

I guess the following
````
origami-fold-node: Tried to construct a node where the children overlap or are not distinct regions:
````
Error is another ticket!? (about what data-structure the server supplies, and what origami expects, I guess)

**Comment by tomterl** [comment]
Hmm - trying to gather data for a follow-up ticket, I don't have folding-related communication in the iph-log buffer, Just the error in Messages with a bunch of (apparently overlapping) ranges.  Does this mean I'm wrong in assuming the foldingRange-registration was successful? Or is the communication caused by lsp-origami not logged if `lsp-log-io` is 't?

**Comment by yyoncho** [comment]
@tomterl 
> I don't have folding-related communication in the iph-log buffer, Just the error in Messages with a bunch of (apparently overlapping) ranges. 

That is odd. You may try to `M-x trace-function RET lsp--get-folding-ranges` to verify that the server has been called. FTR you should look for `textDocument/foldingRange` in the logs.

**Comment by tomterl** [comment]
Trace shows it is called, thanks for the tip. I'll try to cook up an example of what's going on and create a new issue.
