### ISSUE TITLE
intelephense errors (pro license) : foldingRangeProvider

### ISSUE THREAD

**Issue by rileyrg** [emacs-lsp/lsp-origami#5]
Trying the folding functions origami provides and

> Capability not supported by the language server: "foldingRangeProvider"

I googled this and the intelephense author suggested the client (I guess lsp-origami-mode in this case) might have some registration issues and that seems to be resolved according to the link below but folding doesn't work regardless.

Both origami-mode and lsp-origami-mode are enabled and lsp is talking to intelephense.

https://github.com/bmewburn/vscode-intelephense/issues/666

**Comment by tomterl** [comment]
Folding using intelephense and lsp-origami started working for me after updating from melpa today (lsp-mode-20200221.543).

**Comment by tomterl** [comment]
Folding works now in some files, but not all.  Very strange.  I'll report back, if I can get behind which difference causes this.
